### ISSUE TITLE
Requests are hidden

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#129]
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2016/04/01 18:03:05.037 PlexRequests.UI.Modules.SearchModule Trace: Searching for Movie beetlejuice 
2016/04/01 18:03:07.194 PlexRequests.UI.Modules.SearchModule Info: Requesting movie with id 4011 
2016/04/01 18:03:07.254 PlexRequests.UI.Modules.SearchModule Debug: movie with id 4011 doesnt exists 
2016/04/01 18:03:07.416 PlexRequests.UI.Modules.SearchModule Trace: Getting movie info from TheMovieDb 
2016/04/01 18:03:07.443 PlexRequests.UI.Modules.SearchModule Trace: {
  "id": 4011,
  "imdb_id": "tt0094721",
  "title": "Beetlejuice",
  "original_title": "Beetlejuice",
  "original_language": "en",
  "status": "Released",
  "tagline": "He's guaranteed to put some life, in your afterlife.",
  "overview": "Thanks to an untimely demise via drowning, a young couple end up as poltergeists in their New England farmhouse, where they fail to meet the challenge of scaring away the insufferable new owners, who want to make drastic changes. In desperation, the undead newlyweds turn to an expert frightmeister, but he's got a diabolical agenda of his own.",
  "homepage": "",
  "backdrop_path": "/upAwc1kPQJU1ZWeMgEWV8Lp6CWb.jpg",
  "poster_path": "/9QWgpkxjs9Pcb5JfWIw37lL6vYd.jpg",
  "adult": false,
  "video": false,
  "belongs_to_collection": {
    "id": 311946,
    "name": "Beetlejuice Collection",
    "poster_path": null,
    "backdrop_path": null
  },
  "genres": [
    {
      "id": 14,
      "name": "Fantasy"
    },
    {
      "id": 35,
      "name": "Comedy"
    }
  ],
  "release_date": "1988-03-30T00:00:00",
  "revenue": 73326666,
  "budget": 15000000,
  "runtime": 92,
  "popularity": 1.981666,
  "vote_average": 7.0,
  "vote_count": 561,
  "production_companies": [
    {
      "name": "Geffen Pictures",
      "id": 360
    },
    {
      "name": "Geffen Company, The",
      "id": 4354
    }
  ],
  "production_countries": [
    {
      "Iso_3166_1": "US",
      "Name": "United States of America"
    }
  ],
  "spoken_languages": [
    {
      "Iso_639_1": "en",
      "Name": "English"
    }
  ],
  "alternative_titles": null,
  "releases": null,
  "credits": null,
  "images": null,
  "keywords": null,
  "videos": null,
  "translations": null,
  "similar": null,
  "reviews": null,
  "lists": null,
  "changes": null,
  "account_states": null,
  "release_dates": null
} 
2016/04/01 18:03:07.706 PlexRequests.UI.Modules.SearchModule Trace: {
  "Port": 3579,
  "SearchForMovies": true,
  "SearchForTvShows": true,
  "RequireMovieApproval": true,
  "RequireTvShowApproval": true,
  "WeeklyRequestLimit": 0,
  "Id": 1
} 
2016/04/01 18:03:07.757 PlexRequests.UI.Modules.SearchModule Debug: Adding movie to database requests 
2016/04/01 18:07:41.231 PlexRequests.Api.ApiRequest Fatal: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) <0x80a7ca9a0 + 0x001e1> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) <0x80a7ca000 + 0x000bb> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x807aedbf0 + 0x00105> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x807aeba10 + 0x00223> in <filename unknown>:0  Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) <0x80a7ca9a0 + 0x001e1> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) <0x80a7ca000 + 0x000bb> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x807aedbf0 + 0x00105> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x807aeba10 + 0x00223> in <filename unknown>:0 
2016/04/01 18:07:41.297 PlexRequests.Api.ApiRequest Info: [
  {
    "propertyName": "TvdbId",
    "errorMessage": "This series has already been added",
    "attemptedValue": 290853
  }
] 
2016/04/01 18:07:51.123 PlexRequests.UI.Modules.SearchModule Trace: Loading Index 
2016/04/01 18:07:55.876 PlexRequests.UI.Modules.SearchModule Trace: Searching for Movie beetlej 
2016/04/01 18:07:56.665 PlexRequests.UI.Modules.SearchModule Trace: Searching for Movie beetlejuice 
2016/04/01 18:07:58.648 PlexRequests.UI.Modules.SearchModule Info: Requesting movie with id 4011 
2016/04/01 18:07:58.729 PlexRequests.UI.Modules.SearchModule Trace: movie with id 4011 exists 
```

#### Reproduction Steps:

I request a movie, it indicates it's been successfully added, I go to the requests page and it's blank. I try to approve all, I get "Something went wrong". I try to add the movie again and it says it's already requested. So now I have about 3 or 4 phantom requests. I will attach my DB

[PlexRequests.zip](https://github.com/tidusjar/PlexRequests.Net/files/200482/PlexRequests.zip)

**Comment by tedrock** [comment]
Also if I don't have require approval on the same thing happens and they don't get passed to CouchPotato.

**Comment by tidusjar** [comment]
Can you please check your filter? The filters seem a bit broken sometimes.

**Comment by tedrock** [comment]
I tried each filter option while under Movies and Shows, nothing shows. Unless you mean something else when you say "check your filters".

**Comment by tidusjar** [comment]
@tedrock I have just imported your DB to see what is going on an the title Beetlejuice has been added and I can see it in the requests page.

Now what has happened when you have tried to approve all, is that in `v1.5.x` the Approve All will approve Movies and TV Shows, the reason the error is there is because we have an error back from Sonarr, this is usually because the series already exists in Sonarr so it won't let us add it. This has also been fixed in `v1.6`

tedrock, are you able to go on Gitter to discuss further and for me to do a remote session to take a look at whats going on?

**Comment by tedrock** [comment]
I just discovered it's only happening in Chrome (Version 49.0.2623.110 m) on my computer (Windows 7). Firefox shows them, and Chrome on my iPad and friends Surfice shows all the requests fine. I have launched Chrome with all extensions disabled and the issue still occurs. The div id tvList and movieList don't appear to want to show. I'll try rebooting my PC next to see if that does anything.

**Comment by tedrock** [comment]
Fixed it, cleared my cache in chrome :disappointed:

**Comment by tidusjar** [comment]
Man that sucks, I wonder what it was caching since the content was in the DOM...
