### ISSUE TITLE
Wizard not working with base URL

### ISSUE THREAD

**Issue by mfrelink** [tidusjar/PlexRequests.Net#526]
#### Plex Requests.Net Version:
1.9.1

#### Operating System:
Ubuntu 16.04

#### Reproduction Steps:
One of the latest updates introduced the new wizard, but will redirect to the web server root /wizard without taking the configured base URL into account. When base URL is set for example to request, wizard should point to /request/wizard. 

This is a problem when previously you had configured plexrequest with a base URL but didn't configure enough so it triggers the wizard (don't know what the reason is). This renders plexrequest in an unusable state.

**Comment by Do-while-Bacon** [comment]
Same issue on CentOS 7. I rolled back to 1.8.4.

Could not complete the wizard due to the base URL issue. Wizard should not be triggered when upgrading anyway.

**Comment by tidusjar** [comment]
I think this is because the migration code is incorrect, it assumes you upgrade to each version (which is incorrect) 1.8.4 > 1.9.0 > 1.9.1

**Comment by onedr0p** [comment]
Fixed in #531

**Comment by tidusjar** [comment]
The fresh install the wizard should appear (That's who it's aimed at).

Thanks for the PR too!

**Comment by SaskiFX** [comment]
Is this in 1.9.2? I updated from 1.8.4 tonight and when I started the app, the wizard is appearing even though I have a database.

But when I attempt to request the auth token, the URL it's posting is still missing my baseurl

**Comment by tidusjar** [comment]
There is a problem in the migration code. Can you update to 1.9.0 > 1.9.1 > 1.9.2?

**Comment by SaskiFX** [comment]
I can try that. Do I have to do anything other than copy 1.9.0 in, start the service, stop the service, upgrade to the next? Or do I need to login each time?

**Comment by tidusjar** [comment]
Nope, just start it, wait for a few seconds then do the next!

**Comment by SaskiFX** [comment]
Still broke. So I did each incremental update, and when I get back to 1.9.2 and start it I'm still getting the wizard, which is still not working for me. When I inspect the button and then press it in firefox, I get:

POST 
XHR 
https://<mysite>/wizard/plexAuth [HTTP/1.1 404 Not Found 1ms]

so the baseurl is not getting attached still right there. 

Of course I have a DB and a config, so I'm not sure why the wizard is coming up anyway.

**Comment by anarion80** [comment]
Hmm... It seems to work for me.
I deleted everything, installed 1.9.0, started the service, set everything up in the wizard (including the baseUrl). Then I stopped the service, unzipped 1.9.1 over, started the service to check if it's working (it was), so stopped again, unzipped 1.9.2 over and started yet again. I have the latest version now with baseUrl working for me. <- but this is not a wizard again. I guess this is the workaround for a problem in migration code. I hope the real fix will be in the new release soon.

**Comment by tidusjar** [comment]
Did you make sure you waited a bit for the db to update when you went through each version? There was a bug in the migration code that requires you to go through each build and it will then migrate the code when the application is starting up. 

If you want you can send me your db and I'll fix it for you. Tidusjar@gmail.com

**Comment by diabl0w** [comment]
I am having this issue right now on a fresh install.. no option for base_url in startup wizard for jellyfin

**Comment by onedr0p** [comment]
This is ombi not jellyfin

**Comment by onedr0p** [comment]
I think you should open a new instead of necro'ing a 4 year old issue that had nothing to do with what you posted.
