### ISSUE TITLE
Dev branch keep saying there is a update

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#686]
After auto update to the dev branch, it keeps saying there is a update

Status page says:
Version:  1.1000 version
and the newest verion is 1.10987

**Comment by tidusjar** [comment]
Is this fixed now?

**Comment by SuperPotatoMen** [comment]
i'm not sure, i rollbacked the code, i will check it later this day.

**Comment by SuperPotatoMen** [comment]
Fixed

**Comment by SuperPotatoMen** [comment]
Still a problem.

Current Version:  1.10.1000
New Version:  1.10.1009
