### ISSUE TITLE
Unable to send Newsletter test email to admin

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#717]
Plex Requests.Net Version: Development 1.10.1020

Operating System: Windows 10 Home

Reproduction Steps:

Whenever you send a test email to Admin it displays the following message in a green box:
"Value cannot be null. Parameter name: source".

If any logs will help, please let me know and I'll post them to pastebin and post the link.

**Comment by tidusjar** [comment]
Hmmm... It's working for me...
What Plex version are you running? Also can you send me a screenshot of that page?

**Comment by chrisausbun** [comment]
Just upgraded to the newest dev version: 1.10.1023. First tried using the Automatic Update (Beta) and that didn't work, but I know that's just a cool feature that's still in Beta so I didn't bother reporting that as an issue. I've attached the screenshot below and yes, my email settings are correct. I did a test and I received it just fine.
![status](https://cloud.githubusercontent.com/assets/22944072/20863348/a9c52ed0-b97c-11e6-8004-ca946f639be6.png)

**Comment by chrisausbun** [comment]
Just to be on the safe side, I've listed a screenshot of my email settings below:

![email settings](https://cloud.githubusercontent.com/assets/22944072/20863364/13176d12-b97d-11e6-92bf-a199804d0663.png)

**Comment by chrisausbun** [comment]
Oh, and I'm not too sure if it helps or not but this has been happening ever since version 1.9.7. Thanks a lot for looking into this. I greatly appreciate it.

**Comment by jneljeff** [comment]
Seconded.  I mentioned this in thread for issue #696

**Comment by SuperPotatoMen** [comment]
Fixed

**Comment by tidusjar** [comment]
Does anyone want to try a Early Access Preview build to confirm I have fixed the issue?

**Comment by chrisausbun** [comment]
I'd be willing to try it but would there be any issue with rolling back to a previous version since I'm currently on Dev 1.10.1031?


On Dec 8, 2016, at 4:14 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Does anyone want to try a Early Access Preview build to confirm I have fixed the issue?

-

**Comment by tidusjar** [comment]
There should be no issue's at all
https://ci.appveyor.com/project/tidusjar/requestplex/build/1.10.1033/artifacts

**Comment by chrisjace** [comment]
fyi - just tested with build 1033, and the issue with Newsletter "value cannot be null. Parameter name: source" / Unable to send Newsletter test e-mail to admin still persists.

**Comment by chrisausbun** [comment]
Still not fixed with 1.10.1039. I will now try the EAP build.



On Dec 8, 2016, at 8:12 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #717<https://github.com/tidusjar/PlexRequests.Net/issues/717>.

-

**Comment by chrisjace** [comment]
Same here, tested and still not fixed with 1.10.1039.

Below is log excerpt:
--
System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.OrderedEnumerable`2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IComparer`1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49cdcc99ee2>:0 at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0 at PlexRequests.Services.Jobs.RecentlyAdded.GenerateTvHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel tv, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x0014d] in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Test () [0x0001b] in :0 at PlexRequests.UI.Modules.AdminModule.RecentlyAddedTest () [0x00015] in :0
--

**Comment by chrisausbun** [comment]
Still nada with EAP build 1.10.1033. I noticed there is an update available for the EAP build. The updated version is 1.10.1037, would you like me to try that?



On Dec 8, 2016, at 8:50 AM, chrisjace <notifications@github.com<mailto:notifications@github.com>> wrote:


Same here, tested and still not fixed with 1.10.1039.

Below is log excerpt:
System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.OrderedEnumerable2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable1[T] source, System.Func2[T,TResult] keySelector, System.Collections.Generic.IComparer1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49cdcc99ee2>:0 at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable1[T] source, System.Func2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0 at PlexRequests.Services.Jobs.RecentlyAdded.GenerateTvHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel tv, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x0014d] in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Test () [0x0001b] in :0 at PlexRequests.UI.Modules.AdminModule.RecentlyAddedTest () [0x00015] in :0

-

**Comment by tidusjar** [comment]
No can you use the Dev build as that contains the additional logging. Thanks chris for that log

**Comment by chrisausbun** [comment]
Ok no problem. I'm on the latest dev version 1.10.1039 and I've listed the error log below:


System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending) at PlexRequests.Services.Jobs.RecentlyAdded.GenerateTvHtml(RecentlyAddedModel tv, PlexSettings plexSettings, StringBuilder sb) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 209 at PlexRequests.Services.Jobs.RecentlyAdded.Start(NewletterSettings newletterSettings, Boolean testEmail) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 137 at PlexRequests.Services.Jobs.RecentlyAdded.Test() in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 110 at PlexRequests.UI.Modules.AdminModule.RecentlyAddedTest() in C:\projects\requestplex\PlexRequests.UI\Modules\Admin\AdminModule.cs:line 1053

On Dec 8, 2016, at 10:24 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


No can you use the Dev build as that contains the additional logging. Thanks chris for that log

-

**Comment by tidusjar** [comment]
Ok with both of those logs I think I found the issue.
Here is a new build with the fix, thank you guys for helping test this.
https://ci.appveyor.com/project/tidusjar/requestplex/build/1.10.1041/artifacts

**Comment by chrisjace** [comment]
Test e-mail to admin works for me now, thanks!

**Comment by chrisausbun** [comment]
Works for me as well. Thanks for all the hard work.

I did however try using the automatics updated and that hasn't worked once for me. If you'd like I can open another bug for that but I know it's just a Beta feature so I don't know if it's really worth reporting just yet.



On Dec 8, 2016, at 12:31 PM, chrisjace <notifications@github.com<mailto:notifications@github.com>> wrote:


Test e-mail to admin works for me now, thanks!

-

**Comment by tidusjar** [comment]
Yeah if you could open a new bug with any details that would great! Glad
it's working now. Phew

**Comment by SuperPotatoMen** [comment]
@chrisausbun  good to know the problem is fixed now! Can you make a new issue for the automatic update with the information you have?
I will close this one :)

**Comment by chrisausbun** [comment]
Sure thing.


On Dec 8, 2016, at 1:54 PM, SuperPotatoMen <notifications@github.com<mailto:notifications@github.com>> wrote:


@chrisausbun<https://github.com/chrisausbun> good to know the problem is fixed now! Can you make a new issue for the automatic update with the information you have?
I will close this one :)

-

**Comment by chrisausbun** [comment]
So, the good news is I received the email and it says that it successfully sent but the bad news is, it's not showing any content. I had originally thought that maybe since it was still indexing, it just took awhile for it to be able to query for recently added items but now I'm not too sure. My library is rather large. It's around 15TBs just in case that has anything to do with it. Is there anyway you can tell if it only show recently added items from now on out?

![blank newsletter](https://cloud.githubusercontent.com/assets/22944072/21031153/dde1dd3e-bd56-11e6-9517-067822e9c223.png)

**Comment by SuperPotatoMen** [comment]
@chrisausbun  pleas open a new issue for this one.

**Comment by chrisausbun** [comment]
Will do



On Dec 8, 2016, at 3:19 PM, SuperPotatoMen <notifications@github.com<mailto:notifications@github.com>> wrote:


@chrisausbun<https://github.com/chrisausbun> pleas open a new issue for this one.

-
